// Generated by a ProtoBuf compiler.  DO NOT EDIT!
// Source: Example.pbs

#include <cstdint>
#include <string>
#include <vector>


struct SubMessage
{
    int64_t req_int64;
    int32_t opt_sint32;
    uint64_t req_uint64;
    uint32_t opt_fixed32;
    float req_float;
    std::string opt_string = "DEFAULT STRING";
    std::vector<int32_t> rep_int32;
    std::vector<uint64_t> rep_uint64;
    std::vector<double> rep_double;

    bool has_req_int64 = false;
    bool has_opt_sint32 = false;
    bool has_req_uint64 = false;
    bool has_opt_fixed32 = false;
    bool has_req_float = false;
    bool has_opt_string = false;

    void ProtoBufEncode(ProtoBufEncoder &pb);
    void ProtoBufDecode(std::string_view buffer);
};


void SubMessage::ProtoBufEncode(ProtoBufEncoder &pb)
{
    pb.put_int64(1, req_int64);
    pb.put_sint32(2, opt_sint32);
    pb.put_uint64(3, req_uint64);
    pb.put_fixed32(4, opt_fixed32);
    pb.put_float(5, req_float);
    pb.put_string(6, opt_string);
    pb.put_repeated_int32(11, rep_int32);
    pb.put_repeated_uint64(12, rep_uint64);
    pb.put_repeated_double(13, rep_double);

}

void SubMessage::ProtoBufDecode(std::string_view buffer)
{
    ProtoBufDecoder pb(buffer);

    while(pb.get_next_field())
    {
        switch(pb.field_num)
        {
            case 1: pb.get_int64(&req_int64, &has_req_int64); break;
            case 2: pb.get_sint32(&opt_sint32, &has_opt_sint32); break;
            case 3: pb.get_uint64(&req_uint64, &has_req_uint64); break;
            case 4: pb.get_fixed32(&opt_fixed32, &has_opt_fixed32); break;
            case 5: pb.get_float(&req_float, &has_req_float); break;
            case 6: pb.get_string(&opt_string, &has_opt_string); break;
            case 11: pb.get_repeated_int32(&rep_int32); break;
            case 12: pb.get_repeated_uint64(&rep_uint64); break;
            case 13: pb.get_repeated_double(&rep_double); break;

            default: pb.skip_field();
        }
    }

    if(! has_req_int64) {
        throw std::runtime_error("Decoded protobuf has no required field SubMessage.req_int64");
    }

    if(! has_req_uint64) {
        throw std::runtime_error("Decoded protobuf has no required field SubMessage.req_uint64");
    }

    if(! has_req_float) {
        throw std::runtime_error("Decoded protobuf has no required field SubMessage.req_float");
    }

}

struct MainMessage
{
    uint32_t opt_uint32;
    int64_t req_sfixed64;
    double opt_double = 3.14;
    std::string req_bytes;
    SubMessage req_msg;
    std::vector<int32_t> rep_sint32;
    std::vector<uint64_t> rep_fixed64;
    std::vector<std::string> rep_string;
    std::vector<SubMessage> rep_msg;

    bool has_opt_uint32 = false;
    bool has_req_sfixed64 = false;
    bool has_opt_double = false;
    bool has_req_bytes = false;
    bool has_req_msg = false;

    void ProtoBufEncode(ProtoBufEncoder &pb);
    void ProtoBufDecode(std::string_view buffer);
};


void MainMessage::ProtoBufEncode(ProtoBufEncoder &pb)
{
    pb.put_uint32(1, opt_uint32);
    pb.put_sfixed64(2, req_sfixed64);
    pb.put_double(3, opt_double);
    pb.put_bytes(4, req_bytes);
    pb.put_message(5, req_msg);
    pb.put_repeated_sint32(11, rep_sint32);
    pb.put_repeated_fixed64(12, rep_fixed64);
    pb.put_repeated_string(13, rep_string);
    pb.put_repeated_message(14, rep_msg);

}

void MainMessage::ProtoBufDecode(std::string_view buffer)
{
    ProtoBufDecoder pb(buffer);

    while(pb.get_next_field())
    {
        switch(pb.field_num)
        {
            case 1: pb.get_uint32(&opt_uint32, &has_opt_uint32); break;
            case 2: pb.get_sfixed64(&req_sfixed64, &has_req_sfixed64); break;
            case 3: pb.get_double(&opt_double, &has_opt_double); break;
            case 4: pb.get_bytes(&req_bytes, &has_req_bytes); break;
            case 5: pb.get_message(&req_msg, &has_req_msg); break;
            case 11: pb.get_repeated_sint32(&rep_sint32); break;
            case 12: pb.get_repeated_fixed64(&rep_fixed64); break;
            case 13: pb.get_repeated_string(&rep_string); break;
            case 14: pb.get_repeated_message(&rep_msg); break;

            default: pb.skip_field();
        }
    }

    if(! has_req_sfixed64) {
        throw std::runtime_error("Decoded protobuf has no required field MainMessage.req_sfixed64");
    }

    if(! has_req_bytes) {
        throw std::runtime_error("Decoded protobuf has no required field MainMessage.req_bytes");
    }

    if(! has_req_msg) {
        throw std::runtime_error("Decoded protobuf has no required field MainMessage.req_msg");
    }

}
